# Generated by Django 4.2 on 2024-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('tracking_code', models.CharField(max_length=8)),
                ('payer', models.CharField(max_length=100)),
                ('payer_phone_number', models.CharField(max_length=12)),
                ('origin_card', models.CharField(max_length=12)),
                ('bank', models.CharField(max_length=30)),
            ],
        ),
    ]
