# Generated by Django 4.2 on 2023-12-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sales and Marketing', 'Sales and Marketing'), ('Software and Programming', 'Software and Programming'), ('Finantial and Accounting', 'Finantial and Accounting'), ('Official', 'Official'), ('DigitalMarketing', 'DigitalMarketing'), ('ContentProduction', 'ContentProduction'), ('It Devops Server', 'It Devops Server'), ('Design', 'Design'), ('Customer Support', 'Customer Support'), ('Industrial Enginerring', 'Industrial Enginerring'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Human Resources', 'Human Resources'), ('Servise Force', 'Servise Force'), ('Education', 'Education'), ('Inventory', 'Inventory'), ('Cinema Feild', 'Cinema Feild'), ('Mechanical and Aerospace Engineering', 'Mechanical and Aerospace Engineering'), ('Technician', 'Technician'), ('Tourism', 'Tourism'), ('Product Manager', 'Product Manager'), ('Medical', 'Medical'), ('TTransportation', 'Transportation'), ('HotelManagement', 'HotelManagement'), ('Public Relations', 'Public Relations'), ('Chemical Petronum', 'Chemical Petronum'), ('Insurance Management', 'Insurance Management'), ('Mine and Metalogy Engineering', 'Mine and Metalogy Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('TE', 'Txtile Engineering'), ('Pharmacology', 'Pharmacology'), ('Journalist', 'Journalist'), ('Agricultural Engineering', 'Agricultural Engineering'), ('Musical and Sound Engineering', 'Musical and Sound Engineering'), ('Physical Education', 'Physical Education')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=300)),
                ('Industry', models.CharField(max_length=200)),
                ('EstablishedYear', models.CharField(max_length=200)),
                ('Introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_adress', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=10)),
                ('residence', models.CharField(max_length=100)),
                ('cv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tehran', 'Tehran'), ('Khorasan Razavi', 'Khorasan Razavi'), ('Isfahan', 'Isfahan'), ('Alborz', 'Alborz'), ('Fars', 'Fars'), ('Qom', 'Qom'), ('East Azerbaijan', 'East Azerbaijan'), ('Mazandaran', 'Mazandaran'), ('Gilan', 'Gilan'), ('Kerman', 'Kerman'), ('Khozestan', 'Khozestan'), ('Yazd', 'Yazd'), ('Markazi', 'Markazi'), ('Qazvin', 'Qazvin'), ('Hormozgan', 'Hormozgan'), ('Golestan', 'Golestan'), ('Zanjan', 'Zanjan'), ('Hamedan', 'Hamedan'), ('Semnan', 'Semnan'), ('West Azerbaijan', 'West Azerbaijan'), ('Boushehr', 'Boushehr'), ('Kordestan', 'Kordestan'), ('Kermanshah', 'Kermanshah'), ('Sistan Balouchestan', 'Sistan Balouchestan'), ('Charmahal Bakhtiari', 'Charmahal Bakhtiari'), ('Ardebil', 'Ardebil'), ('Kohkiluyeh and Boyerahmad', 'Kohkiluyeh and Boyerahmad'), ('Ilam', 'Ilam'), ('Khorasan Jonoubi', 'Khorasan Jonoubi'), ('Khorestan Shomali', 'Khorestan Shomali'), ('Lorestan', 'Lorestan')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Sales and Marketing', 'Sales and Marketing'), ('Software and Programming', 'Software and Programming'), ('Finantial and Accounting', 'Finantial and Accounting'), ('Official', 'Official'), ('DigitalMarketing', 'DigitalMarketing'), ('ContentProduction', 'ContentProduction'), ('It Devops Server', 'It Devops Server'), ('Design', 'Design'), ('Customer Support', 'Customer Support'), ('Industrial Enginerring', 'Industrial Enginerring'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Human Resources', 'Human Resources'), ('Servise Force', 'Servise Force'), ('Education', 'Education'), ('Inventory', 'Inventory'), ('Cinema Feild', 'Cinema Feild'), ('Mechanical and Aerospace Engineering', 'Mechanical and Aerospace Engineering'), ('Technician', 'Technician'), ('Tourism', 'Tourism'), ('Product Manager', 'Product Manager'), ('Medical', 'Medical'), ('TTransportation', 'Transportation'), ('HotelManagement', 'HotelManagement'), ('Public Relations', 'Public Relations'), ('Chemical Petronum', 'Chemical Petronum'), ('Insurance Management', 'Insurance Management'), ('Mine and Metalogy Engineering', 'Mine and Metalogy Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('TE', 'Txtile Engineering'), ('Pharmacology', 'Pharmacology'), ('Journalist', 'Journalist'), ('Agricultural Engineering', 'Agricultural Engineering'), ('Musical and Sound Engineering', 'Musical and Sound Engineering'), ('Physical Education', 'Physical Education')], max_length=230)),
                ('location', models.CharField(choices=[('Tehran', 'Tehran'), ('Khorasan Razavi', 'Khorasan Razavi'), ('Isfahan', 'Isfahan'), ('Alborz', 'Alborz'), ('Fars', 'Fars'), ('Qom', 'Qom'), ('East Azerbaijan', 'East Azerbaijan'), ('Mazandaran', 'Mazandaran'), ('Gilan', 'Gilan'), ('Kerman', 'Kerman'), ('Khozestan', 'Khozestan'), ('Yazd', 'Yazd'), ('Markazi', 'Markazi'), ('Qazvin', 'Qazvin'), ('Hormozgan', 'Hormozgan'), ('Golestan', 'Golestan'), ('Zanjan', 'Zanjan'), ('Hamedan', 'Hamedan'), ('Semnan', 'Semnan'), ('West Azerbaijan', 'West Azerbaijan'), ('Boushehr', 'Boushehr'), ('Kordestan', 'Kordestan'), ('Kermanshah', 'Kermanshah'), ('Sistan Balouchestan', 'Sistan Balouchestan'), ('Charmahal Bakhtiari', 'Charmahal Bakhtiari'), ('Ardebil', 'Ardebil'), ('Kohkiluyeh and Boyerahmad', 'Kohkiluyeh and Boyerahmad'), ('Ilam', 'Ilam'), ('Khorasan Jonoubi', 'Khorasan Jonoubi'), ('Khorestan Shomali', 'Khorestan Shomali'), ('Lorestan', 'Lorestan')], max_length=230)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.company')),
            ],
        ),
    ]
