# Generated by Django 4.2 on 2023-12-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_category_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
