# Generated by Django 4.2 on 2024-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_job_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='candidate',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='email_adress',
            field=models.EmailField(max_length=254),
        ),
    ]
